### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by AlbertoAEC** [ekzGuille/wh2me#23]
Mejoras de cara a la introducción de un número por pegado desde otra fuente:

Sería interesante que admita un teléfono con espacios en blanco entre medias, para los formatos “999 99 99 99”.

También que si el numero al introducirlo ya contiene el numero de país, que sobreescriba sobre la caja de texto designada a tal efecto.
Ej: +34 999 99 99 99 -> +34 | 999999999

**Comment by ekzGuille** [comment]
1)  Hacer un replace 

```js
string.replace(/\s/g, '')
```

2) Hacerlo para España únicamente. Si contiene un *+34* o un *34* delante y la longitud es de `9 + 2` o `9 + 3` volcarlo en el input tras hacer el replace correspondiente.
